//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWindowsService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieCaseEntities : DbContext
    {
        public MovieCaseEntities()
            : base("name=MovieCaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie_Belongs_To_Collection> Movie_Belongs_To_Collection { get; set; }
        public virtual DbSet<Movie_Genres> Movie_Genres { get; set; }
        public virtual DbSet<Movie_Production_Companies> Movie_Production_Companies { get; set; }
        public virtual DbSet<Movie_Production_Countries> Movie_Production_Countries { get; set; }
        public virtual DbSet<Movie_Spoken_Languages> Movie_Spoken_Languages { get; set; }
        public virtual DbSet<MovieList> MovieList { get; set; }
    }
}
