//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Spoken_Languages
    {
        public int sid { get; set; }
        public Nullable<int> movie_id { get; set; }
        public string english_name { get; set; }
        public string iso_639_1 { get; set; }
        public string name { get; set; }
    }
}
