//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieList
    {
        public int sid { get; set; }
        public Nullable<int> id { get; set; }
        public string adult { get; set; }
        public string backdrop_path { get; set; }
        public string belongs_to_collection { get; set; }
        public Nullable<decimal> budget { get; set; }
        public string homepage { get; set; }
        public string imdb_id { get; set; }
        public string original_language { get; set; }
        public string original_title { get; set; }
        public string overview { get; set; }
        public Nullable<decimal> popularity { get; set; }
        public string poster_path { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<long> revenue { get; set; }
        public Nullable<int> runtime { get; set; }
        public string status { get; set; }
        public string tagline { get; set; }
        public string title { get; set; }
        public string video { get; set; }
        public Nullable<decimal> vote_average { get; set; }
        public Nullable<int> vote_count { get; set; }
    }
}
